User Story 1
MaggieSchuetz/capstone-project pull request #10
Opened 2022-03-08 16:42 UTC by MaggieSchuetz

Issue:  https://github.com/MaggieSchuetz/capstone-project/issues/1

Can anyone tell me why me header is not sticky? :persevere: I added where it should stick (top), the parent has no overflow-property set as far as I'm aware, so I don't know what else to check.

Also why does it not work in vercel?

2022-03-08 18:00 UTC, ttaannjjaa requested changes
A lot of work done in this step, looks really good to me 👍

2022-03-08 20:30 UTC, Quaquaro reviewed
Great work so far.
If you have any questions about my comments, please feel free to contact me. I would be happy to help you with your form component and with the integration of fonts.
See you later :)

2022-03-08 20:30 UTC, Quaquaro commented on src/components/FormNew.js
> +    <Card className="forForm">
Now it is important to give each input a name attribute that is exactly the same as the key value in your initialFormData. 
Then you have to adjust the value and add the onChange event.
Example for your first input:
`<input
  name="date"
  type="date"
  value={formData.date}
  onChange={handleChange}>`

2022-03-08 20:30 UTC, Quaquaro commented on src/components/FormNew.js
> +    console.log('hello');
The following should be written here:
`e.preventDefault();
const newEntry = {
date: formData.date, 
title: formData.title,
text: formData.text}`

2022-03-08 20:30 UTC, Quaquaro commented on src/components/FormNew.js
> +    document.getElementById('form').reset();
The following should be written here:
`const journalEntriesArray= [newEntry, ...items???]` The name of the array in which your previous entries are located.
`setEntries(journalEntriesArray)`This should actually be output from the component, since you want to create your entries elsewhere with the result.
`setFormData(initialFormData)` this will reset the form

2022-03-09 07:49 UTC, Quaquaro reviewed
Fix the header test and ignore the useEffect warning in Form.js than you be able to deploy it on vercel

2022-03-09 07:49 UTC, Quaquaro commented on src/components/Form.js
> +    enableButton();
Put this over line 77 :`// eslint-disable-next-line react-hooks/exhaustive-deps` It is the Vercel error with the use effect therefore it cannot be deployed.

2022-03-09 08:26 UTC, MaggieSchuetz commented on src/components/FormNew.js
> +  // const [messageDate, setMessageDate] = useState('(required)');
Yes, I accidentally added & uploaded this file (I forgot that I had it to work out some bugs)

2022-03-09 08:27 UTC, MaggieSchuetz commented on src/components/Header.spec.js
> +    const header = screen.getByRole('heading');
Thank you!

2022-03-09 08:28 UTC, MaggieSchuetz commented on src/components/FormNew.js
> +
I accidentally added & uploaded this file (I forgot that I had it to work out some bugs)

2022-03-09 08:28 UTC, MaggieSchuetz commented on src/components/Form.js
> +    enableButton();
THANK YOU!

2022-03-09 08:29 UTC, MaggieSchuetz commented on src/components/Form.js
> +        aria-labelledby="label-date"
Thanks! Forgot to remove it after trying out some stuff!

2022-03-09 09:21 UTC, MaggieSchuetz commented on public/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com" />
Yes, that would be awesome! Thank you :)

2022-03-09 09:33 UTC, ahohnsen approved these changes
Looks all good to me :) nice work.

2022-03-09 09:36 UTC, merged